// src/workers/messageTypes.js
// IPC Message types for worker communication
// ═══════════════════════════════════════════════════════════════

const MessageTypes = {
  // Dashboard Worker
  DASHBOARD_GET_BLOCKED_IPS: 'DASHBOARD_GET_BLOCKED_IPS',
  DASHBOARD_BLOCK_IP: 'DASHBOARD_BLOCK_IP',
  DASHBOARD_UNBLOCK_IP: 'DASHBOARD_UNBLOCK_IP',
  DASHBOARD_GET_CONFIG: 'DASHBOARD_GET_CONFIG',
  DASHBOARD_SAVE_CONFIG: 'DASHBOARD_SAVE_CONFIG',
  DASHBOARD_GET_RULES: 'DASHBOARD_GET_RULES',
  DASHBOARD_SEND_EVENT: 'DASHBOARD_SEND_EVENT',
  DASHBOARD_GET_EVENTS: 'DASHBOARD_GET_EVENTS',

  // Pipeline Worker
  PIPELINE_PROCESS_REQUEST: 'PIPELINE_PROCESS_REQUEST',
  PIPELINE_BLOCK_IP: 'PIPELINE_BLOCK_IP',
  PIPELINE_UNBLOCK_IP: 'PIPELINE_UNBLOCK_IP',
  PIPELINE_GET_STATUS: 'PIPELINE_GET_STATUS',
  PIPELINE_START: 'PIPELINE_START',
  PIPELINE_STOP: 'PIPELINE_STOP',

  // ML Worker
  ML_TRAIN: 'ML_TRAIN',
  ML_ANALYZE: 'ML_ANALYZE',
  ML_QUERY_LOGS: 'ML_QUERY_LOGS',
  ML_GET_STATUS: 'ML_GET_STATUS',
  ML_RULES_CHANGED: 'ML_RULES_CHANGED',

  // Logging Worker
  LOG_WRITE: 'LOG_WRITE',
  LOG_READ: 'LOG_READ',
  LOG_GET_FILES: 'LOG_GET_FILES',
  LOG_GET_CONFIG: 'LOG_GET_CONFIG',
  LOG_SET_CONFIG: 'LOG_SET_CONFIG',
  LOG_ADMIN_EVENT: 'LOG_ADMIN_EVENT',

  // Responses
  RESPONSE_SUCCESS: 'RESPONSE_SUCCESS',
  RESPONSE_ERROR: 'RESPONSE_ERROR',
};

module.exports = { MessageTypes };